### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [miso-xyz/miso-xyz#1]

**Comment by miso-xyz** [comment]
use [https://discord.id/](https://discord.id/) to retrieve my discord tag

a discord user ID is set on the account creation and doesn't change, what you've referenced was a discord tag, which can be changed at anytime.

![image](https://user-images.githubusercontent.com/61099345/107853137-34d57780-6e0c-11eb-99e2-80b28ebffc8f.png)

Edit: ive sent you a friend request

**Comment by graysuit** [comment]
@miso-xyz 
Looks like I have new thing to learn and you are teacher of that.
Sorry for my mistake.

Okay you can see my msg at discord.
